// AUTO-GENERATED by tools-flowbg/gen-props-data.py from docs/rose-horizon-props/*/manifest.json
// Do not hand-edit positions here -- regenerate from the manifests instead, so this data
// always matches what ingest actually measured off the approved design.

export interface RoseHorizonProp {
  id: string;
  /** Percent of the section's own box (position: relative wrapper), matching manifest.json's pct block. */
  x: number;
  y: number;
  w: number;
  h: number;
  src: string;
  /** Spans most of both axes at once (a border/frame, not an icon) -- exempt from
   *  PropLayer's reserved-zone collision avoidance; see gen-props-data.py for why. */
  frame?: boolean;
}

export const PROP_DEPTH = 1.3; // foreground -- CLAUDE.md's T7 depth calibration: 1.2-1.5 = foreground props

export const ROSE_HORIZON_PROPS: Record<string, RoseHorizonProp[]> = {
  welcome: [
    { id: 'floral-arch-and-roses', x: 50.0, y: 50.38, w: 100.0, h: 99.23, src: '/templates/rose-horizon/assets/welcome/floral-arch-and-roses.webp', frame: true }, // Floral arch and roses
  ],
  walimah: [
    { id: 'rose-wreathed-crescent-moon-and-star', x: 52.59, y: 43.69, w: 62.21, h: 32.08, src: '/templates/rose-horizon/assets/walimah/rose-wreathed-crescent-moon-and-star.webp' }, // Rose-wreathed crescent moon and star
    { id: 'cream-rose-bloom', x: 25.83, y: 63.03, w: 43.85, h: 24.65, src: '/templates/rose-horizon/assets/walimah/cream-rose-bloom.webp' }, // Cream rose bloom
    { id: 'dusty-blue-grey-rose-bloom', x: 74.17, y: 24.32, w: 41.11, h: 24.12, src: '/templates/rose-horizon/assets/walimah/dusty-blue-grey-rose-bloom.webp' }, // Dusty blue-grey rose bloom
  ],
  rsvp: [
    { id: 'cream-rose-bloom', x: 70.51, y: 85.76, w: 49.41, h: 25.06, src: '/templates/rose-horizon/assets/rsvp/cream-rose-bloom.webp' }, // Cream rose bloom
    { id: 'envelope-with-a-rose-wax-seal', x: 23.83, y: 15.06, w: 43.55, h: 27.54, src: '/templates/rose-horizon/assets/rsvp/envelope-with-a-rose-wax-seal.webp' }, // Envelope with a rose wax seal
    { id: 'blush-pink-rose-bloom', x: 51.61, y: 34.76, w: 31.35, h: 13.62, src: '/templates/rose-horizon/assets/rsvp/blush-pink-rose-bloom.webp' }, // Blush-pink rose bloom
  ],
  itinerary: [
    { id: 'blush-pink-rose-bloom', x: 26.22, y: 83.76, w: 52.44, h: 32.49, src: '/templates/rose-horizon/assets/itinerary/blush-pink-rose-bloom.webp' }, // Blush-pink rose bloom
    { id: 'rose-ringed-hourglass', x: 52.83, y: 43.78, w: 42.58, h: 30.37, src: '/templates/rose-horizon/assets/itinerary/rose-ringed-hourglass.webp' }, // Rose-ringed hourglass
    { id: 'baby-s-breath-sprig', x: 81.88, y: 12.77, w: 36.23, h: 24.94, src: '/templates/rose-horizon/assets/itinerary/baby-s-breath-sprig.webp' }, // Baby's breath sprig
  ],
  wishes: [
    { id: 'dusty-blue-grey-rose-bloom', x: 80.76, y: 90.12, w: 38.48, h: 19.75, src: '/templates/rose-horizon/assets/wishes/dusty-blue-grey-rose-bloom.webp' }, // Dusty blue-grey rose bloom
    { id: 'open-scroll-with-a-feather-quill', x: 50.49, y: 17.84, w: 39.06, h: 15.15, src: '/templates/rose-horizon/assets/wishes/open-scroll-with-a-feather-quill.webp' }, // Open scroll with a feather quill
    { id: 'baby-s-breath-sprig', x: 13.87, y: 9.35, w: 27.73, h: 18.46, src: '/templates/rose-horizon/assets/wishes/baby-s-breath-sprig.webp' }, // Baby's breath sprig
  ],
  photobooth: [
    { id: 'floral-corner-picture-frame', x: 50.2, y: 19.16, w: 86.33, h: 24.76, src: '/templates/rose-horizon/assets/photobooth/floral-corner-picture-frame.webp' }, // Floral-corner picture frame
    { id: 'cream-rose-bloom', x: 19.29, y: 88.65, w: 38.57, h: 22.7, src: '/templates/rose-horizon/assets/photobooth/cream-rose-bloom.webp' }, // Cream rose bloom
  ],
};
