// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingInvite.Data;

#nullable disable

namespace WeddingInvite.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906133447_AddTemplate10SunnySafari")]
    partial class AddTemplate10SunnySafari
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WeddingInvite.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("WEDDING");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRsvpOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxPax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name1")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name2")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowCapacityWarning")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasFilter("[Domain] IS NOT NULL");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("WeddingInvite.Models.EventFeature", b =>
                {
                    b.Property<int>("EventFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnabledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("EventId", "FeatureId")
                        .IsUnique();

                    b.ToTable("EventFeatures");
                });

            modelBuilder.Entity("WeddingInvite.Models.EventTemplateConfig", b =>
                {
                    b.Property<int>("EventTemplateConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EventTemplateConfigId");

                    b.HasIndex("EventId", "ConfigKey")
                        .IsUnique();

                    b.ToTable("TemplateConfigs");
                });

            modelBuilder.Entity("WeddingInvite.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeatureId");

                    b.HasIndex("FeatureCode")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 594, DateTimeKind.Utc).AddTicks(3290),
                            Description = "Allow guests to upload and share photos from the wedding",
                            FeatureCode = "PHOTO_BOOTH",
                            FeatureName = "Photo Booth",
                            IsActive = true,
                            IsPremium = true,
                            SortOrder = 1
                        },
                        new
                        {
                            FeatureId = 2,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 594, DateTimeKind.Utc).AddTicks(3380),
                            Description = "Online gift registry with payment links",
                            FeatureCode = "E_GIFTS",
                            FeatureName = "E-Gifts Registry",
                            IsActive = false,
                            IsPremium = true,
                            SortOrder = 2
                        },
                        new
                        {
                            FeatureId = 3,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 594, DateTimeKind.Utc).AddTicks(3380),
                            Description = "Use your own domain name (e.g., johnandmary.wedding)",
                            FeatureCode = "CUSTOM_DOMAIN",
                            FeatureName = "Custom Domain",
                            IsActive = true,
                            IsPremium = true,
                            SortOrder = 3
                        },
                        new
                        {
                            FeatureId = 4,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 594, DateTimeKind.Utc).AddTicks(3380),
                            Description = "Guest RSVP and attendance tracking",
                            FeatureCode = "RSVP",
                            FeatureName = "RSVP Management",
                            IsActive = true,
                            IsPremium = false,
                            SortOrder = 0
                        },
                        new
                        {
                            FeatureId = 5,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 594, DateTimeKind.Utc).AddTicks(3380),
                            Description = "Guests can leave wishes and messages",
                            FeatureCode = "WISHES",
                            FeatureName = "Wishes & Guestbook",
                            IsActive = true,
                            IsPremium = false,
                            SortOrder = 0
                        },
                        new
                        {
                            FeatureId = 6,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Assign guests to tables and manage seating arrangements",
                            FeatureCode = "SEATING",
                            FeatureName = "Seating Management",
                            IsActive = true,
                            IsPremium = true,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestSide")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongRequest")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestId");

                    b.HasIndex("EventId");

                    b.HasIndex("TableId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WeddingInvite.Models.ItineraryItem", b =>
                {
                    b.Property<int>("ItineraryItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItineraryItemId");

                    b.HasIndex("EventId");

                    b.ToTable("ItineraryItems");
                });

            modelBuilder.Entity("WeddingInvite.Models.LandingContentItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LandingContent");
                });

            modelBuilder.Entity("WeddingInvite.Models.LandingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Cta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CtaHref")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LandingItems");
                });

            modelBuilder.Entity("WeddingInvite.Models.LandingSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LandingSections");
                });

            modelBuilder.Entity("WeddingInvite.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageId");

                    b.HasIndex("PackageCode")
                        .IsUnique();

                    b.HasIndex("PackageName")
                        .IsUnique();

                    b.ToTable("Packages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Basic wedding invitation with RSVP and guestbook",
                            IsActive = true,
                            PackageCode = "FREE",
                            PackageName = "Free",
                            Price = 0m,
                            SortOrder = 1
                        },
                        new
                        {
                            PackageId = 2,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full-featured wedding invitation with photo booth, RSVP, and guestbook",
                            IsActive = true,
                            PackageCode = "PREMIUM",
                            PackageName = "Premium",
                            Price = 99m,
                            SortOrder = 2
                        },
                        new
                        {
                            PackageId = 1000,
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Everything in Premium, plus your own custom domain",
                            IsActive = true,
                            PackageCode = "PRO",
                            PackageName = "Pro",
                            Price = 199m,
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.PackageFeature", b =>
                {
                    b.Property<int>("PackageFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PackageFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("PackageId", "FeatureId")
                        .IsUnique();

                    b.ToTable("PackageFeatures");

                    b.HasData(
                        new
                        {
                            PackageFeatureId = 1,
                            FeatureId = 4,
                            PackageId = 1
                        },
                        new
                        {
                            PackageFeatureId = 2,
                            FeatureId = 5,
                            PackageId = 1
                        },
                        new
                        {
                            PackageFeatureId = 3,
                            FeatureId = 1,
                            PackageId = 2
                        },
                        new
                        {
                            PackageFeatureId = 4,
                            FeatureId = 4,
                            PackageId = 2
                        },
                        new
                        {
                            PackageFeatureId = 5,
                            FeatureId = 5,
                            PackageId = 2
                        },
                        new
                        {
                            PackageFeatureId = 6,
                            FeatureId = 6,
                            PackageId = 2
                        },
                        new
                        {
                            PackageFeatureId = 1000,
                            FeatureId = 1,
                            PackageId = 1000
                        },
                        new
                        {
                            PackageFeatureId = 1001,
                            FeatureId = 3,
                            PackageId = 1000
                        },
                        new
                        {
                            PackageFeatureId = 1002,
                            FeatureId = 4,
                            PackageId = 1000
                        },
                        new
                        {
                            PackageFeatureId = 1003,
                            FeatureId = 5,
                            PackageId = 1000
                        },
                        new
                        {
                            PackageFeatureId = 1004,
                            FeatureId = 6,
                            PackageId = 1000
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("WeddingInvite.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Caption")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TemplateSlot")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("GUEST");

                    b.HasKey("PhotoId");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("EventId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("WeddingInvite.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TableId");

                    b.HasIndex("EventId");

                    b.ToTable("Tables");
                });

            modelBuilder.Entity("WeddingInvite.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ComponentPath")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("WEDDING");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAuthored")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StagesJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("Templates");

                    b.HasData(
                        new
                        {
                            TemplateId = 1,
                            ComponentPath = "Template1",
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 595, DateTimeKind.Utc).AddTicks(6320),
                            Description = "Elegant rose and pink design with top navigation",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = false,
                            PrimaryColor = "#f43f5e",
                            SecondaryColor = "#ec4899",
                            SortOrder = 1,
                            TemplateCode = "classic-rose",
                            TemplateName = "Classic Rose",
                            ThumbnailUrl = "",
                            Tier = "FREE"
                        },
                        new
                        {
                            TemplateId = 2,
                            ComponentPath = "Template2",
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 595, DateTimeKind.Utc).AddTicks(6420),
                            Description = "Luxurious yellow and gold single-page design with floating navigation",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = true,
                            PrimaryColor = "#eab308",
                            SecondaryColor = "#f59e0b",
                            SortOrder = 2,
                            TemplateCode = "golden-elegance",
                            TemplateName = "Golden Elegance",
                            ThumbnailUrl = "",
                            Tier = "PREMIUM"
                        },
                        new
                        {
                            TemplateId = 3,
                            ComponentPath = "Template3",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Botanical green theme with couple portrait and extra image slots",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = true,
                            PrimaryColor = "#16a34a",
                            SecondaryColor = "#86efac",
                            SortOrder = 3,
                            TemplateCode = "garden-romance",
                            TemplateName = "Garden Romance",
                            ThumbnailUrl = "",
                            Tier = "PREMIUM"
                        },
                        new
                        {
                            TemplateId = 4,
                            ComponentPath = "Template4",
                            CreatedDate = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Clean cream and black editorial design with torn-paper dividers, live countdown, and timeline schedule",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = true,
                            PrimaryColor = "#1C1C1A",
                            SecondaryColor = "#8A8A80",
                            SortOrder = 4,
                            TemplateCode = "minimal-noir",
                            TemplateName = "Minimal Noir",
                            ThumbnailUrl = "",
                            Tier = "PREMIUM"
                        },
                        new
                        {
                            TemplateId = 6,
                            ComponentPath = "Template6",
                            CreatedDate = new DateTime(2026, 5, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Enchanted fairy garden with glowing 3D fireflies, falling petals, and immersive forest scenes",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = true,
                            PrimaryColor = "#f7c6d7",
                            SecondaryColor = "#a8d5a2",
                            SortOrder = 6,
                            TemplateCode = "fairy-garden",
                            TemplateName = "Fairy Garden",
                            ThumbnailUrl = "",
                            Tier = "PREMIUM"
                        },
                        new
                        {
                            TemplateId = 7,
                            ComponentPath = "Template7",
                            CreatedDate = new DateTime(2026, 7, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sepia line-engraved Roman garden with parallax scenes, a sideways-panning ceremony colonnade, and an expanding RSVP seating chart",
                            EventTypes = "WEDDING",
                            IsActive = true,
                            IsAuthored = false,
                            IsPremium = true,
                            PrimaryColor = "#3D3833",
                            SecondaryColor = "#C9BFAE",
                            SortOrder = 7,
                            TemplateCode = "roman-garden",
                            TemplateName = "Roman Garden",
                            ThumbnailUrl = "",
                            Tier = "PRO"
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.TemplateConfigDefault", b =>
                {
                    b.Property<int>("TemplateConfigDefaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TemplateConfigDefaultId");

                    b.HasIndex("TemplateId", "ConfigKey")
                        .IsUnique();

                    b.ToTable("TemplateConfigDefaults");
                });

            modelBuilder.Entity("WeddingInvite.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EventId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 9, 6, 13, 34, 46, 764, DateTimeKind.Utc).AddTicks(4500),
                            Email = "admin@wedding-cms.com",
                            IsActive = true,
                            PasswordHash = "$2a$11$EEWcUchDKrqwWy.ACR2Mo./gMNBfvLCvgDxB3wh8.7OQiDIzPQliW",
                            Role = "SUPER_ADMIN",
                            Tier = "FREE"
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("WishId");

                    b.HasIndex("EventId");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("WeddingInvite.Models.Event", b =>
                {
                    b.HasOne("WeddingInvite.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeddingInvite.Models.Template", "Template")
                        .WithMany("Events")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WeddingInvite.Models.EventFeature", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany("EventFeatures")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingInvite.Models.Feature", "Feature")
                        .WithMany("EventFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("WeddingInvite.Models.EventTemplateConfig", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.Guest", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany("Guests")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingInvite.Models.Table", "Table")
                        .WithMany("Guests")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("WeddingInvite.Models.ItineraryItem", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany("ItineraryItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.PackageFeature", b =>
                {
                    b.HasOne("WeddingInvite.Models.Feature", "Feature")
                        .WithMany()
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingInvite.Models.Package", "Package")
                        .WithMany("PackageFeatures")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("WeddingInvite.Models.PasswordResetToken", b =>
                {
                    b.HasOne("WeddingInvite.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WeddingInvite.Models.Photo", b =>
                {
                    b.HasOne("WeddingInvite.Models.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany("Photos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.Table", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.TemplateConfigDefault", b =>
                {
                    b.HasOne("WeddingInvite.Models.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("WeddingInvite.Models.User", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.Wish", b =>
                {
                    b.HasOne("WeddingInvite.Models.Event", "Event")
                        .WithMany("Wishes")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("WeddingInvite.Models.Event", b =>
                {
                    b.Navigation("EventFeatures");

                    b.Navigation("Guests");

                    b.Navigation("ItineraryItems");

                    b.Navigation("Photos");

                    b.Navigation("Wishes");
                });

            modelBuilder.Entity("WeddingInvite.Models.Feature", b =>
                {
                    b.Navigation("EventFeatures");
                });

            modelBuilder.Entity("WeddingInvite.Models.Package", b =>
                {
                    b.Navigation("PackageFeatures");
                });

            modelBuilder.Entity("WeddingInvite.Models.Table", b =>
                {
                    b.Navigation("Guests");
                });

            modelBuilder.Entity("WeddingInvite.Models.Template", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
