// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeddingInvite.Data;

#nullable disable

namespace WeddingInvite.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260123114919_AddFeaturesAndPhotos")]
    partial class AddFeaturesAndPhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("WeddingInvite.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("FeatureId");

                    b.HasIndex("FeatureCode")
                        .IsUnique();

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            CreatedDate = new DateTime(2026, 1, 23, 11, 49, 19, 186, DateTimeKind.Utc).AddTicks(6290),
                            Description = "Allow guests to upload and share photos from the wedding",
                            FeatureCode = "PHOTO_BOOTH",
                            FeatureName = "Photo Booth",
                            IsActive = true,
                            IsPremium = true,
                            SortOrder = 1
                        },
                        new
                        {
                            FeatureId = 2,
                            CreatedDate = new DateTime(2026, 1, 23, 11, 49, 19, 186, DateTimeKind.Utc).AddTicks(6370),
                            Description = "Online gift registry with payment links",
                            FeatureCode = "E_GIFTS",
                            FeatureName = "E-Gifts Registry",
                            IsActive = false,
                            IsPremium = true,
                            SortOrder = 2
                        },
                        new
                        {
                            FeatureId = 3,
                            CreatedDate = new DateTime(2026, 1, 23, 11, 49, 19, 186, DateTimeKind.Utc).AddTicks(6370),
                            Description = "Use your own domain name (e.g., johnandmary.wedding)",
                            FeatureCode = "CUSTOM_DOMAIN",
                            FeatureName = "Custom Domain",
                            IsActive = false,
                            IsPremium = true,
                            SortOrder = 3
                        },
                        new
                        {
                            FeatureId = 4,
                            CreatedDate = new DateTime(2026, 1, 23, 11, 49, 19, 186, DateTimeKind.Utc).AddTicks(6370),
                            Description = "Guest RSVP and attendance tracking",
                            FeatureCode = "RSVP",
                            FeatureName = "RSVP Management",
                            IsActive = true,
                            IsPremium = false,
                            SortOrder = 0
                        },
                        new
                        {
                            FeatureId = 5,
                            CreatedDate = new DateTime(2026, 1, 23, 11, 49, 19, 186, DateTimeKind.Utc).AddTicks(6370),
                            Description = "Guests can leave wishes and messages",
                            FeatureCode = "WISHES",
                            FeatureName = "Wishes & Guestbook",
                            IsActive = true,
                            IsPremium = false,
                            SortOrder = 0
                        });
                });

            modelBuilder.Entity("WeddingInvite.Models.Guest", b =>
                {
                    b.Property<int>("GuestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrideOrGroomSide")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAttending")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAttendees")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SongRequest")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeddingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GuestId");

                    b.HasIndex("WeddingId");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("WeddingInvite.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("WeddingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhotoId");

                    b.HasIndex("WeddingId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("WeddingInvite.Models.Wedding", b =>
                {
                    b.Property<int>("WeddingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrideName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CoupleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroomName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("VenueAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WeddingDate")
                        .HasColumnType("TEXT");

                    b.HasKey("WeddingId");

                    b.HasIndex("CoupleName")
                        .IsUnique();

                    b.ToTable("Weddings");
                });

            modelBuilder.Entity("WeddingInvite.Models.WeddingFeature", b =>
                {
                    b.Property<int>("WeddingFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Configuration")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EnabledDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FeatureId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeddingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WeddingFeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("WeddingId", "FeatureId")
                        .IsUnique();

                    b.ToTable("WeddingFeatures");
                });

            modelBuilder.Entity("WeddingInvite.Models.Wish", b =>
                {
                    b.Property<int>("WishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("WeddingId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WishId");

                    b.HasIndex("WeddingId");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("WeddingInvite.Models.Guest", b =>
                {
                    b.HasOne("WeddingInvite.Models.Wedding", "Wedding")
                        .WithMany("Guests")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("WeddingInvite.Models.Photo", b =>
                {
                    b.HasOne("WeddingInvite.Models.Wedding", "Wedding")
                        .WithMany("Photos")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("WeddingInvite.Models.WeddingFeature", b =>
                {
                    b.HasOne("WeddingInvite.Models.Feature", "Feature")
                        .WithMany("WeddingFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WeddingInvite.Models.Wedding", "Wedding")
                        .WithMany("WeddingFeatures")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("WeddingInvite.Models.Wish", b =>
                {
                    b.HasOne("WeddingInvite.Models.Wedding", "Wedding")
                        .WithMany("Wishes")
                        .HasForeignKey("WeddingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wedding");
                });

            modelBuilder.Entity("WeddingInvite.Models.Feature", b =>
                {
                    b.Navigation("WeddingFeatures");
                });

            modelBuilder.Entity("WeddingInvite.Models.Wedding", b =>
                {
                    b.Navigation("Guests");

                    b.Navigation("Photos");

                    b.Navigation("WeddingFeatures");

                    b.Navigation("Wishes");
                });
#pragma warning restore 612, 618
        }
    }
}
