#!/usr/bin/env python3
"""Generate data/roseHorizonProps.ts from the committed ingest manifests — real measured
positions, not hand-transcribed, to avoid the kind of transcription error that's bitten this
run before (see session log: 4/13 auto-generated names were wrong on first read).
"""
import json
import pathlib

WT = pathlib.Path("/Users/helmyheiry/wedding-invite-app/.worktrees/rose-horizon-20260908")
PROPS_DIR = WT / "docs/rose-horizon-props"
ASSETS_DIR = WT / "frontend/public/templates/rose-horizon/assets"
OUT = WT / "frontend/components/templates/Template11-rosehorizon/data/roseHorizonProps.ts"

SECTIONS = ["welcome", "walimah", "rsvp", "itinerary", "wishes", "photobooth"]
DEPTH = 1.3  # foreground, per CLAUDE.md's own T7 calibration note (1.2-1.5 = foreground props)

entries = []
for section in SECTIONS:
    manifest = json.loads((PROPS_DIR / section / "manifest.json").read_text())
    section_assets_dir = ASSETS_DIR / section
    section_assets_dir.mkdir(parents=True, exist_ok=True)
    for p in manifest["props"]:
        if not p.get("matched"):
            continue
        name = p["name"]
        slug = "".join(c if c.isalnum() else "-" for c in name.lower()).strip("-")
        while "--" in slug:
            slug = slug.replace("--", "-")
        src_webp = PROPS_DIR / section / f"{name}.webp"
        dest = section_assets_dir / f"{slug}.webp"
        dest.write_bytes(src_webp.read_bytes())
        entries.append(dict(
            section=section, id=slug, name=name,
            src=f"/templates/rose-horizon/assets/{section}/{slug}.webp",
            x=p["pct"]["x"], y=p["pct"]["y"], w=p["pct"]["w"], h=p["pct"]["h"],
        ))

lines = [
    "// AUTO-GENERATED by tools-flowbg/gen-props-data.py from docs/rose-horizon-props/*/manifest.json",
    "// Do not hand-edit positions here -- regenerate from the manifests instead, so this data",
    "// always matches what ingest actually measured off the approved design.",
    "",
    "export interface RoseHorizonProp {",
    "  id: string;",
    "  /** Percent of the section's own box (position: relative wrapper), matching manifest.json's pct block. */",
    "  x: number;",
    "  y: number;",
    "  w: number;",
    "  h: number;",
    "  src: string;",
    "}",
    "",
    "export const PROP_DEPTH = 1.3; // foreground -- CLAUDE.md's T7 depth calibration: 1.2-1.5 = foreground props",
    "",
    "export const ROSE_HORIZON_PROPS: Record<string, RoseHorizonProp[]> = {",
]
by_section: dict[str, list] = {s: [] for s in SECTIONS}
for e in entries:
    by_section[e["section"]].append(e)

for section in SECTIONS:
    lines.append(f"  {section}: [")
    for e in by_section[section]:
        lines.append(
            f"    {{ id: '{e['id']}', x: {e['x']}, y: {e['y']}, w: {e['w']}, h: {e['h']}, "
            f"src: '{e['src']}' }}, // {e['name']}"
        )
    lines.append("  ],")
lines.append("};")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT} -- {len(entries)} props across {len(SECTIONS)} sections")
for section in SECTIONS:
    print(f"  {section}: {len(by_section[section])} props")
