import { TemplateConfigField } from './api/types';

const COMMON_FIELDS: TemplateConfigField[] = [
  // ── Invitation section ──────────────────────────────────────────────────────
  {
    key: 'invite.heading',
    label: 'Welcome Heading',
    defaultValue: 'Together with their families',
    maxLength: 50,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.heading.align',
    label: 'Heading Alignment',
    defaultValue: 'center',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['left', 'center', 'right'],
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.heading.animation',
    label: 'Heading Animation',
    defaultValue: 'none',
    maxLength: 20,
    richText: false,
    fieldType: 'select',
    options: ['none', 'fade', 'slide', 'typewriter'],
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.heading.color',
    label: 'Heading Color',
    defaultValue: '',
    maxLength: 20,
    richText: false,
    fieldType: 'color',
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.heading.shadow',
    label: 'Heading Shadow',
    defaultValue: 'none',
    maxLength: 20,
    richText: false,
    fieldType: 'select',
    options: ['none', 'soft', 'strong', 'glow'],
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.body',
    label: 'Invitation Message',
    defaultValue: 'We joyfully invite you to share in the celebration of our wedding',
    maxLength: 200,
    richText: true,
    fieldType: 'richtext',
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.body.align',
    label: 'Message Alignment',
    defaultValue: 'center',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['left', 'center', 'right'],
    adminOnly: false,
    section: 'invitation',
  },

  // ── General section ─────────────────────────────────────────────────────────
  {
    key: 'general.showIslamicDate',
    label: 'Show Islamic (Hijri) Date',
    defaultValue: 'false',
    maxLength: 5,
    richText: false,
    fieldType: 'boolean',
    adminOnly: false,
    section: 'general',
  },
  {
    key: 'general.showAddToCalendar',
    label: 'Show "Add to Calendar" button',
    defaultValue: 'false',
    maxLength: 5,
    richText: false,
    fieldType: 'boolean',
    adminOnly: false,
    section: 'general',
  },
  {
    key: 'general.showVenueMap',
    label: 'Show venue map',
    defaultValue: 'false',
    maxLength: 5,
    richText: false,
    fieldType: 'boolean',
    adminOnly: false,
    section: 'general',
  },
  {
    key: 'section.order',
    label: 'Section Order',
    defaultValue: 'welcome,walimah,rsvp,itinerary,wishes,photobooth',
    maxLength: 100,
    richText: false,
    fieldType: 'text',
    adminOnly: true,
    section: 'general',
  },

  // ── Ceremony section ────────────────────────────────────────────────────────
  {
    key: 'walimah.body',
    label: 'Ceremony / Walimah Details',
    defaultValue: '',
    maxLength: 500,
    richText: true,
    fieldType: 'richtext',
    adminOnly: false,
    section: 'ceremony',
  },
  {
    key: 'walimah.body.align',
    label: 'Ceremony Text Alignment',
    defaultValue: 'center',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['left', 'center', 'right'],
    adminOnly: false,
    section: 'ceremony',
  },

  // ── RSVP section ────────────────────────────────────────────────────────────
  {
    key: 'rsvp.subtitle',
    label: 'RSVP Subtitle',
    defaultValue: 'Kindly reply by one week before the wedding date',
    maxLength: 80,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'rsvp',
  },

  // ── Wishes section ──────────────────────────────────────────────────────────
  {
    key: 'wish.prompt',
    label: 'Wish Prompt',
    defaultValue: 'Leave a message for the happy couple',
    maxLength: 80,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'wishes',
  },

  // ── Styling / Background section ────────────────────────────────────────────
  {
    key: 'section.welcome.bg',
    label: 'Welcome Section Background',
    defaultValue: '',
    maxLength: 500,
    richText: false,
    fieldType: 'image',
    adminOnly: false,
    section: 'styling',
  },
  {
    key: 'section.ceremony.bg',
    label: 'Ceremony Section Background',
    defaultValue: '',
    maxLength: 500,
    richText: false,
    fieldType: 'image',
    adminOnly: false,
    section: 'styling',
  },
  {
    key: 'section.celebration.bg',
    label: 'Celebration Section Background',
    defaultValue: '',
    maxLength: 500,
    richText: false,
    fieldType: 'image',
    adminOnly: false,
    section: 'styling',
  },

  // ── Footer section ──────────────────────────────────────────────────────────
  {
    key: 'footer.tagline',
    label: 'Footer Tagline',
    defaultValue: 'Made with love for our special day',
    maxLength: 80,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'footer',
  },

  // ── Navigation — super admin only ───────────────────────────────────────────
  {
    key: 'nav.invite',
    label: 'Nav: Invitation',
    defaultValue: 'Invitation',
    maxLength: 20,
    richText: false,
    fieldType: 'text',
    adminOnly: true,
    section: 'navigation',
  },
  {
    key: 'nav.rsvp',
    label: 'Nav: RSVP',
    defaultValue: 'RSVP',
    maxLength: 20,
    richText: false,
    fieldType: 'text',
    adminOnly: true,
    section: 'navigation',
  },
  {
    key: 'nav.wishes',
    label: 'Nav: Wishes',
    defaultValue: 'Wishes',
    maxLength: 20,
    richText: false,
    fieldType: 'text',
    adminOnly: true,
    section: 'navigation',
  },
  {
    key: 'nav.photos',
    label: 'Nav: Photos',
    defaultValue: 'Photos',
    maxLength: 20,
    richText: false,
    fieldType: 'text',
    adminOnly: true,
    section: 'navigation',
  },

  // ── Music ───────────────────────────────────────────────────────────────────
  {
    key: 'music.url',
    label: 'Background Music URL',
    fieldType: 'text',
    defaultValue: '',
    maxLength: 500,
    richText: false,
    adminOnly: false,
    section: 'music',
  },
  {
    key: 'music.loop',
    label: 'Loop Music',
    fieldType: 'boolean',
    defaultValue: 'true',
    maxLength: 5,
    richText: false,
    adminOnly: false,
    section: 'music',
  },
];

const TEMPLATE3_EXTRA_FIELDS: TemplateConfigField[] = [
  {
    key: 'invite.theme_label',
    label: 'Theme Banner',
    defaultValue: 'Garden Romance',
    maxLength: 30,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.countdown_prefix',
    label: 'Countdown Prefix',
    defaultValue: 'Days until we say I do',
    maxLength: 30,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
];

const TEMPLATE6_EXTRA_FIELDS: TemplateConfigField[] = [
  // ── Scene / 3D controls ─────────────────────────────────────────────────────
  {
    key: 'scene.quality',
    label: '3D Quality',
    defaultValue: 'auto',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['auto', 'high', 'low', 'off'],
    adminOnly: false,
    section: 'scene',
  },
  {
    key: 'scene.firefly.count',
    label: 'Firefly Count',
    defaultValue: 'medium',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['low', 'medium', 'high'],
    adminOnly: false,
    section: 'scene',
  },
  {
    key: 'scene.petal.color',
    label: 'Petal Colour',
    defaultValue: '#f7c6d7',
    maxLength: 20,
    richText: false,
    fieldType: 'color',
    adminOnly: false,
    section: 'scene',
  },
  {
    key: 'scene.petal.count',
    label: 'Falling Petal Density',
    defaultValue: 'medium',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['none', 'low', 'medium', 'high'],
    adminOnly: false,
    section: 'scene',
  },
  {
    key: 'scene.bloom',
    label: 'Firefly Glow (Bloom)',
    defaultValue: 'true',
    maxLength: 5,
    richText: false,
    fieldType: 'boolean',
    adminOnly: false,
    section: 'scene',
  },
  {
    key: 'scene.fog.color',
    label: 'Forest Fog Colour',
    defaultValue: '#0d1a0e',
    maxLength: 20,
    richText: false,
    fieldType: 'color',
    adminOnly: true,
    section: 'scene',
  },
  {
    key: 'scene.environment',
    label: 'Lighting Preset',
    defaultValue: 'forest',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['forest', 'night', 'dawn'],
    adminOnly: true,
    section: 'scene',
  },
  // ── T6 invitation extras ────────────────────────────────────────────────────
  {
    key: 'invite.enchantment_label',
    label: 'Theme Badge Text',
    defaultValue: 'Enchanted Garden',
    maxLength: 30,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'invite.firefly_greeting',
    label: 'Firefly Intro Line',
    defaultValue: 'Follow the light to our garden',
    maxLength: 60,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
];

const TEMPLATE5_EXTRA_FIELDS: TemplateConfigField[] = [
  {
    key: 'invite.layout',
    label: 'Invitation Layout',
    defaultValue: 'classic',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['classic', 'minimal', 'ornate'],
    adminOnly: false,
    section: 'invitation',
  },
  {
    key: 'template.bg',
    label: 'Page Background Image',
    defaultValue: '',
    maxLength: 500,
    richText: false,
    fieldType: 'image',
    adminOnly: false,
    section: 'styling',
  },
  {
    key: 'template.bgSize',
    label: 'Background Size',
    defaultValue: 'cover',
    maxLength: 10,
    richText: false,
    fieldType: 'select',
    options: ['cover', 'contain', 'auto'],
    adminOnly: false,
    section: 'styling',
  },
  {
    key: 'template.bgPosition',
    label: 'Background Position',
    defaultValue: 'center',
    maxLength: 20,
    richText: false,
    fieldType: 'select',
    options: ['center', 'top center', 'bottom center', 'left center', 'right center'],
    adminOnly: false,
    section: 'styling',
  },
  {
    key: 'invite.countdown_prefix',
    label: 'Countdown Prefix',
    defaultValue: 'Counting down to our special day',
    maxLength: 60,
    richText: false,
    fieldType: 'text',
    adminOnly: false,
    section: 'invitation',
  },
  // ── T5 text element colours & shadows ─────────────────────────────────────────
  { key: 'names.bride.color',      label: 'Bride Name Color',        fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'styling' },
  { key: 'names.bride.shadow',     label: 'Bride Name Shadow',       fieldType: 'select', defaultValue: 'none', maxLength: 10, richText: false, adminOnly: false, options: ['none', 'soft', 'strong', 'glow'], section: 'styling' },
  { key: 'names.groom.color',      label: 'Groom Name Color',        fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'styling' },
  { key: 'names.groom.shadow',     label: 'Groom Name Shadow',       fieldType: 'select', defaultValue: 'none', maxLength: 10, richText: false, adminOnly: false, options: ['none', 'soft', 'strong', 'glow'], section: 'styling' },
  { key: 'names.ampersand.color',  label: 'Ampersand (&) Color',     fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'styling' },
  { key: 'countdown.label.color',  label: 'Countdown Label Color',   fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'invitation' },
  { key: 'countdown.number.color', label: 'Countdown Number Color',  fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'invitation' },
  { key: 'ceremony.title.color',   label: 'Ceremony Title Color',    fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'ceremony' },
  { key: 'ceremony.title.shadow',  label: 'Ceremony Title Shadow',   fieldType: 'select', defaultValue: 'none', maxLength: 10, richText: false, adminOnly: false, options: ['none', 'soft', 'strong', 'glow'], section: 'ceremony' },
  { key: 'ceremony.names.color',   label: 'Ceremony Names Color',    fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'ceremony' },
  { key: 'ceremony.names.shadow',  label: 'Ceremony Names Shadow',   fieldType: 'select', defaultValue: 'none', maxLength: 10, richText: false, adminOnly: false, options: ['none', 'soft', 'strong', 'glow'], section: 'ceremony' },
  { key: 'section.heading.color',  label: 'Section Heading Color',   fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'styling' },
  { key: 'section.heading.shadow', label: 'Section Heading Shadow',  fieldType: 'select', defaultValue: 'none', maxLength: 10, richText: false, adminOnly: false, options: ['none', 'soft', 'strong', 'glow'], section: 'styling' },
  { key: 'footer.tagline.color',   label: 'Footer Tagline Color',    fieldType: 'color',  defaultValue: '', maxLength: 20, richText: false, adminOnly: false, section: 'footer' },
];

const TEMPLATE_CONFIGS: Record<number, TemplateConfigField[]> = {
  1: COMMON_FIELDS,
  2: COMMON_FIELDS,
  3: [...COMMON_FIELDS, ...TEMPLATE3_EXTRA_FIELDS],
  4: COMMON_FIELDS,
  5: [...COMMON_FIELDS, ...TEMPLATE5_EXTRA_FIELDS],
  6: [...COMMON_FIELDS, ...TEMPLATE6_EXTRA_FIELDS],
};

export function getConfigFields(templateId: number, role: string): TemplateConfigField[] {
  const fields = TEMPLATE_CONFIGS[templateId] ?? COMMON_FIELDS;
  if (role === 'SUPER_ADMIN') return fields;
  return fields.filter((f) => !f.adminOnly);
}

export function buildDefaultConfig(templateId: number): Record<string, string> {
  const fields = TEMPLATE_CONFIGS[templateId] ?? COMMON_FIELDS;
  return Object.fromEntries(fields.map((f) => [f.key, f.defaultValue]));
}
